### ISSUE TITLE
Unable to run on armv7l devices

### ISSUE THREAD

**Issue by Narashiman** [markqvist/LXMF#2]
I am trying to install and test out rns and LXMF on a Cortex A9 device. During the installation I get dependency conflict. As mentioned below. Is there any way i can solve this issue. 

ERROR: Cannot install lxmf because these package versions have conflicting dependencies.

The conflict is caused by:
    rns 0.2.2 depends on cryptography>=3.4.7
    rns 0.2.1 depends on cryptography>=3.4.7

PS: 
Cryptography version currently installed : cryptography-3.2.1-cp35-cp35m-linux_armv7l.whl

**Comment by markqvist** [comment]
RNS 0.2.2 is a very old release from the alpha phase, and should definitely not be used now. Current version is 0.3.3. Is there any specific reason why you are using that?

Also, what happens if you try to install a recent version of cryptography? You should be able to run cryptography 3.4.7 on most devices.

A little more info about the device and linux distro you are using would be useful!

**Comment by Narashiman** [comment]
We are using Ubuntu Xenial OS on an orangePi board. RNS lastest version is installed properly and working fine. But when i want to test out LXMF. I am getting this particular error. I thought it should be something to do with the requirements specified in LXMF package.

**Comment by markqvist** [comment]
Can you please post the output of the following commands:

```
python3 --version
pip3 --version
pip3 list
```

**Comment by Narashiman** [comment]
Hi. I was using Python 3.5 and there were many limitations in the build completely. I had to discard and use a Armian OS with latest updates to get it up and running. I was testing it on Orange Pi zero with 256MB. I am surpriced to see that it was running smoothly.

**Comment by markqvist** [comment]
Good to hear it was just a version compatibility issue. The minimum required Python version for Reticulum and related software is Python 3.6 as of the time of writing.

Thanks for reporting your findings and closing the issue.
